sudo: required
services:
  - docker

before_install:
  - docker build -t ejosafat/docker-course-react -f Dockerfile.dev .

script:
  - docker run ejosafat/docker-course-react npm test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-course-react"
  env: "DockerCourseReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-936513152043"
  bucket_path: "docker-course-react"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"